// vuejs_sample/ex03_router_1/src/views/Counter.vue
<template>
  <h2>{{ count }}</h2>
  <button @click="inc">inc</button>
  <button @click="dec">dec</button>
  <button @click="setValue(0)">reset</button>
</template>

<script>
export default {
  // data() {
  //     return {
  //         counter : 0
  //     }
  // },
  computed: {
    count() {
      return this.$store.state.count;
    },
  },
  methods: {
    inc() {
      // this.counter += 1
      this.$store.commit("increment");
      console.log(this.$store.state.count);
    },
    dec() {
        this.$store.commit("decrement");

    },
    setValue(val) {
        this.$store.commit({
            type : "setvalue",
            value : val
        });

    }
  },
};
</script>

// react_sample/ex05_redux/src/component/Counter.js
import React, { useEffect } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import counterSlice from '../redux/counterSlice'

const Counter = () => {
	const dispatch = useDispatch();
	const counter = useSelector((state) => state.counter);

	useEffect(() => {
        console.log('Counter init')
		// dispatch();
	}, [dispatch]);

	return (
		<div>
            <h1>Redux Counter</h1>
            <h3>{counter.count}</h3>

            <button onClick={()=> {
                //호출하기 
                dispatch(counterSlice.actions.inc())

            }} > inc </button>

            <button onClick={()=> {
                //인자전달하기 
                dispatch(counterSlice.actions.set({value:1000}))

            }} > set 1000 </button>
        </div>
	);
};

export default Counter;
